let "operation" and "fixedOperationParameters" to be optional
api3dao/ois pull request #43
Opened 2022-11-17 08:13 UTC by metobom

Related to [this](https://github.com/api3dao/airnode/issues/1527) Airnode issue.

2022-11-17 08:45 UTC, bbenligiray commented
I was saying that this is a breaking change and requires a major version bump, but thinking again, making a required optional isn't a breaking change and a minor version bump should be enough.

2022-11-25 12:03 UTC, Siegrift requested changes

2022-11-25 12:03 UTC, Siegrift commented on src/ois.ts
> +    if (endpoint.operation && endpoint.fixedOperationParameters) {
Do we need the `&& endpoint.fixedOperationParameters` part?

2022-11-25 12:03 UTC, Siegrift commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
Do we need optional here? Can't we just require an empty array? This reduces the number of invalid states of the schema, because essentially what you want is "to skip API call make `operation` field undefined and define postProcessing".

2022-11-27 10:26 UTC, metobom commented on src/ois.ts
> +    if (endpoint.operation && endpoint.fixedOperationParameters) {
The absence of both `endpoint.operation` and `endpoint.fixedOperationParameters` is required to skip API call.

2022-11-27 10:26 UTC, metobom commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
Since both are related to API and won't be used, it could be nice if both are optional.

2022-11-28 08:29 UTC, Siegrift commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
The problem with that is `fixedOperationParameters` could be optional for the "regular" endpoints. This is something that was not possible before. I still lean toward making this required.

2022-11-28 09:16 UTC, bbenligiray commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
`fixedOperationParameters` may be optional for when there is an operation defined but it doesn't make sense when there is no operation defined, so the aren't the same thing. If we don't make `fixedOperationParameters` optional, we'll have to specify that it has to empty when there is no `operation` defined and validate for it (so it's still an invalid state).

As I've mentioned [here](https://github.com/api3dao/airnode/issues/1527#issuecomment-1312446403), I think the proper solution is to move `fixedOperationParameters` under `operation` but that's a breaking change that we probably want to avoid. Any alternative solution will be problematic.

2022-11-28 10:41 UTC, Siegrift commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
> If we don't make fixedOperationParameters optional, we'll have to specify that it has to empty when there is no operation defined and validate for it (so it's still an invalid state).

We can have `If "operation" is undefined, then "fixedOperationParameters" must be empty and "postProcessingSpecifications" must not be empty` which covers all of these cases.

2022-11-28 14:04 UTC, bbenligiray commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
> "postProcessingSpecifications" must not be empty

That's oddly opinionated about doing things in `postProcessingSpecifications` and not `preProcessingSpecifications` (or a mix)

2022-11-29 15:39 UTC, metobom commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
`parameters` will be passed to `preProcessingSpecifications` and then the output of it will be passed to `postProcessingSpecifications`. `preProcessingSpecifications` will be used as it is used in any Airnode case. In this scenario, `postProcessingSpecifications` will act like an API that uses raw or pre-processed inputs. An example endpoint with `preProcessingSpecifications` should look like below.

```
{
        "name": "someName",
        "fixedOperationParameters": [],
        "parameters": [
          {
            "name": "date",
            "operationParameter": {
              "in": "path",
              "name": "date"
            }
          }
        ],
        "reservedParameters": [
          {
            "name": "_type",
            "fixed": "int256"
          },
          {
            "name": "_path",
            "fixed": "result"
          },
          {
            "name": "_times",
            "fixed": "1"
          }
        ],
        "preProcessingSpecifications": [
          {
            "environment": "Node 14",
            "timeoutMs": 5000,
            "value": "output = {formattedDate: formatDate(input.date)};"
          }
        ],
        "postProcessingSpecifications": [
          {
            "environment": "Node 14",
            "timeoutMs": 5000,
            "value": "output = {result: doStuffWithFormattedDate(input.formattedDate)}"
          }
        ]
      }
```
We could've used input `date` without pre-processing as well just like a regular endpoint with API call.

2022-11-29 15:51 UTC, bbenligiray commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
So @Siegrift 's validation should be `If "operation" is undefined, then "fixedOperationParameters" must be empty, and "preProcessingSpecifications" or "postProcessingSpecifications" must not be empty` imo

2022-11-29 16:40 UTC, metobom commented on src/ois.ts
> +    fixedOperationParameters: z.array(fixedParameterSchema).optional(),
>  and "preProcessingSpecifications" or "postProcessingSpecifications" must not be empty` imo

In this case we can do both of these right?

```
...

"parameters": [
  {
    "name": "someNumber",
    "operationParameter": {
      "in": "path",
      "name": "someNumber"
    }
  }
],
"preProcessingSpecifications": [
  {
    "environment": "Node 14",
    "timeoutMs": 5000,
    "value": "output = {result: input.someNumber}"
  }
],
"reservedParameters": [
  {
    "fixed": "uint256",
    "name": "_type"
  },
  {
    "fixed": "result",
    "name": "_path"
  },
  {
    "name": "_times"
  }
]

...
```

```
...

"parameters": [
  {
    "name": "someNumber",
    "operationParameter": {
      "in": "path",
      "name": "someNumber"
    }
  }
],
"postProcessingSpecifications": [
  {
    "environment": "Node 14",
    "timeoutMs": 5000,
    "value": "output = {result: input.someNumber}"
  }
],
"reservedParameters": [
  {
    "fixed": "uint256",
    "name": "_type"
  },
  {
    "fixed": "result",
    "name": "_path"
  },
  {
    "name": "_times"
  }
]

...
```

2022-11-30 06:25 UTC, Siegrift commented
> So @Siegrift 's validation should be If "operation" is undefined, then "fixedOperationParameters" must be empty, and "preProcessingSpecifications" or "postProcessingSpecifications" must not be empty imo

Yeah, we can do that.

> In this case we can do both of these right?

Yeah. (And also allow having both).

2022-12-01 12:31 UTC, Siegrift approved these changes

2022-12-01 12:31 UTC, Siegrift commented on src/ois.ts
> +      (!endpoint.postProcessingSpecifications || endpoint.postProcessingSpecifications?.length === 0) &&
Nit: `postProcessingSpecifications!.length` or consider destructuring the properties from the `endpoint` variable above the if. That way you can just do `if (!postProcessingSpecifications)`...

2022-12-01 12:32 UTC, Siegrift commented
👍 LGTM, just one NIT to consider, but otherwise good to go. I guess you want this to be released as well. 

For that we need @aquarat help 🙏

2022-12-01 14:24 UTC, merged